### PR TITLE
Hotfix/allow empty configuration value

### PR DESCRIPTION
**Pull request by martincote2000**
This modification allow to specify empty string as a remplacement value. And an empty string is an accepted value in a configuration file.

In the example below, I would replace the **Var1** by the empty string. Actually, the variable $(Var1) is not replaced.

Ex:
```json
{
   "Var1": "",
   "Foo": "$(Var1)/Something"
}
```

I added some unit tests to cover this situation.

### CODE REVIEW

**Comment by molinch** [comment]
Thanks Martin !
I don't think we need to expose `ConfigurationExists`, change the existing `string.NullOrWhitespace` to simple null checks would be enough to make your new tests pass, see:

In ChainedSubstitutedConfigurationProvider:
```c#
        public bool TryGet(string key, out string value)
        {
            value = _substitutor.GetSubstituted(_config, key);
            return value != null;
        }
```

In ConfigurationSubstitutor:
```c#
        public string GetSubstituted(IConfiguration configuration, string key)
        {
            var value = configuration[key];
            if (value == null) return value;

            return ApplySubstitution(configuration, value);
        }
```

**Comment by martincote2000** [comment]
Hi @molinch , your solution is better! 

Previously, I was tried to allow empty and null values as these are accepted values for json file. But after thinking, null value can be confusing and maybe never used.

So, I revert the code and I change with your recommendation. The new tests are there too.

Thank you for the review!

**Comment by molinch** [comment]
Thanks @martincote2000  for the contribution !

**Comment by martincote2000** [comment]
Hi @molinch 
Is it possible to generate a new version of the nuget with the latest fix?

Thank you!

**Comment by molinch** [comment]
@martincote2000  Just published nuget 1.1.2 :)
https://www.nuget.org/packages/ConfigurationSubstitutor/

**Pull request merged**
